# Site settings
site:  Dan and Cassie's Wedding
name: Dan and Cassie's Wedding
title: Dan and Cassie's Wedding
email: dan.v.carvajal@gmail.com
baseurl: ""
url: "http://dan-cassie.com" # the base hostname & protocol for your site
description: "The office site of Dan and Cassie."
locale: en_us

author:
  name:           Dan and Cassie
  email:          "dan.v.carvajal@gmail.com"

# Build settings
markdown: kramdown

sass:
  style: compressed

# Gems
gems:
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
