# Site settings
site:  Dan and Cassie's Wedding
name: Dan and Cassie's Wedding
title: Dan and Cassie's Wedding
email: dan.v.carvajal@gmail.com
baseurl: ""
url: "http://dan-cassie.com" # the base hostname & protocol for your site
description: "The office site of Dan and Cassie."
locale: en_us

author:
  name:           Dan Carvajal
  email:          "dan.v.carvajal@gmail.com"
  uri:            "https://twitter.com/dan_v_c"
  twitter:        dan_v_c
  google_plus:    DanCarvajal
  github:         DanCarvajal
  linkedin:       DanCarvajal
  fb_id:          648807029
  country:        United States

# Open Graph
fb_admins:          648807029
fb_appid:           508362279313777

# Build settings
markdown: kramdown

sass:
  style: compressed

# Gems
gems:
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
